import { test, expect, type Page } from '@playwright/test'
import type { TaskSnapshot, RuntimeConfig, AuthInfo } from '../../src/types/api'

async function login(page: Page, path: string) {
  await page.goto(path)
  await page.fill('#auth-password', '测试密码')
  await page.click('#auth-submit')
  await expect(page.locator('#app-content')).toBeVisible()
}
async function csrf(page: Page) {
  const response = await page.request.get('/api/auth')
  const auth: AuthInfo = await response.json()
  expect(auth.authenticated).toBe(true)
  return { 'X-CSRF-Token': auth.csrf_token }
}

test('real API settings conflicts merge disjoint edits and require a choice for overlapping edits', async ({ page }) => {
  await login(page, '/settings')
  await page.click('#edit-config-btn')
  await page.fill('#config-form-max_concurrent_tasks', '2')
  const current: RuntimeConfig = await (await page.request.get('/api/config')).json()
  const headers = await csrf(page)
  expect((await page.request.put('/api/config', { headers, data: { revision: current.revision, web_auth_ttl_hours: 12 } })).status()).toBe(200)
  await page.click('#config-submit')
  await expect(page.locator('#config-form-error')).toContainText('配置已被其他操作修改')
  await page.getByRole('button', { name: '读取最新版本并保留输入' }).click()
  await expect(page.locator('#config-form-max_concurrent_tasks')).toHaveValue('2')
  await expect(page.locator('#config-form-web_auth_ttl_hours')).toHaveValue('12')
  await page.click('#config-submit')
  await expect(page.locator('#config-modal')).toHaveCount(0)
  const saved: RuntimeConfig = await (await page.request.get('/api/config')).json()
  expect(saved.max_concurrent_tasks).toBe(2)
  expect(saved.web_auth_ttl_hours).toBe(12)

  await page.click('#edit-config-btn')
  await page.fill('#config-form-web_auth_ttl_hours', '8')
  const baseline: RuntimeConfig = await (await page.request.get('/api/config')).json()
  expect((await page.request.put('/api/config', { headers, data: { revision: baseline.revision, web_auth_ttl_hours: 6 } })).status()).toBe(200)
  await page.click('#config-submit')
  await page.getByRole('button', { name: '读取最新版本并保留输入' }).click()
  const field = page.locator('[data-conflict-field="web_auth_ttl_hours"]')
  await expect(field).toBeVisible()
  await expect(page.locator('#config-submit')).toBeDisabled()
  await field.getByLabel('使用当前输入', { exact: true }).check()
  await page.click('#config-submit')
  await expect(page.locator('#config-modal')).toHaveCount(0)
  const resolved: RuntimeConfig = await (await page.request.get('/api/config')).json()
  expect(resolved.web_auth_ttl_hours).toBe(8)
  expect(resolved.max_concurrent_tasks).toBe(2)
})

test('real task API round trip preserves fields, applies source reset and rejects starting offline', async ({ page }) => {
  await login(page, '/tasks')
  const taskId = 'browser_contract'
  const headers = await csrf(page)
  const baseline: TaskSnapshot = await (await page.request.get('/api/tasks/contract')).json()
  await page.click('#new-task-btn')
  await page.fill('#task-form-id', taskId)
  await page.fill('#task-form-note', '浏览器与真实 API')
  await page.fill('#task-form-source_channel', '-1003333333333')
  await page.fill('#task-form-target_channel', '-1004444444444')
  await page.click('#task-submit')
  const card = page.locator(`[data-card-id="${taskId}"]`)
  await expect(card).toBeVisible()
  const initial: TaskSnapshot = await (await page.request.get(`/api/tasks/${taskId}`)).json()
  expect(Object.keys(initial.config).sort()).toEqual(Object.keys(baseline.config).sort())
  expect(initial.status).toBe('stopped')
  expect(initial.progress.forwarded_count).toBe(0)
  const start = 'start'
  expect((await page.request.post(`/api/tasks/${taskId}/action`, { headers, data: { action: start } })).status()).toBe(503)

  await card.locator('[data-action="edit"]').click()
  await page.fill('#task-form-note', '我的备注')
  const concurrent = { ...initial.config, required_hashtags: ['#真实契约'], source_topic_id: 23 }
  expect((await page.request.put(`/api/tasks/${taskId}`, { headers, data: { ...concurrent, revision: initial.revision, source_reset: { last_message_id: 123, clear_dedup: true } } })).status()).toBe(200)
  await page.click('#task-submit')
  await expect(page.locator('#task-form-error')).toContainText('配置已被其他操作修改')
  await page.getByRole('button', { name: '读取最新版本并保留输入' }).click()
  await expect(page.locator('#task-form-note')).toHaveValue('我的备注')
  await expect(page.locator('#task-form-hashtags')).toHaveValue('#真实契约')
  await expect(page.locator('#source-reset-options')).toHaveCount(0)
  await page.fill('#task-form-source_channel', '-1005555555555')
  await page.fill('#source-reset-id', '456')
  await page.click('#task-submit')
  await page.click('#confirm-ok')
  await expect(page.locator('#task-modal')).toHaveCount(0)
  const saved: TaskSnapshot = await (await page.request.get(`/api/tasks/${taskId}`)).json()
  expect(saved.config.note).toBe('我的备注')
  expect(saved.config.required_hashtags).toEqual(['#真实契约'])
  expect(saved.config.source_topic_id).toBe(23)
  expect(saved.config.source_channel).toBe(-1005555555555)
  expect(saved.progress.last_message_id).toBe(456)
  expect((await page.request.delete(`/api/tasks/${taskId}`, { headers })).status()).toBe(200)
  expect((await page.request.get(`/api/tasks/${taskId}`)).status()).toBe(404)
})
