"""Owned transfer directories and cleanup which excludes active work."""
import hashlib
import json
import os
import re
import shutil
import time
from pathlib import Path

ACTIVE_WORKSPACES = set()
OWNER_FILE = ".tg-forward-owner.json"


def atomic_json(path, data):
    path = Path(path)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


class WorkspaceStore:
    def __init__(self, root):
        self.root = Path(root).expanduser().resolve()

    def open(self, task_id, source, message_ids):
        identity = json.dumps([task_id, source, sorted(message_ids)])
        task_key = hashlib.sha256(task_id.encode()).hexdigest()[:16]
        transfer_key = hashlib.sha256(identity.encode()).hexdigest()[:24]
        path = self.root / ("task_" + task_key) / transfer_key
        if path.is_symlink() or path.parent.is_symlink():
            raise ValueError("Workspace path must not be a symlink")
        path.mkdir(parents=True, exist_ok=True, mode=0o700)
        atomic_json(path / OWNER_FILE, {"task_id": task_id, "source": source, "message_ids": message_ids, "updated_at": time.time()})
        ACTIVE_WORKSPACES.add(path)
        return path

    def release(self, path):
        path = Path(path).resolve()
        ACTIVE_WORKSPACES.discard(path)
        if path.is_dir():
            owner = path / OWNER_FILE
            if owner.exists():
                data = json.loads(owner.read_text())
                data["updated_at"] = time.time()
                atomic_json(owner, data)

    def directories(self):
        if not self.root.is_dir():
            return []
        result = []
        for owner in self.root.glob("task_*/*/" + OWNER_FILE):
            if owner.is_symlink() or owner.parent.is_symlink() or owner.parent.parent.is_symlink():
                continue
            try:
                data = json.loads(owner.read_text())
                if isinstance(data.get("task_id"), str):
                    result.append((owner.parent, data))
            except (OSError, ValueError, AttributeError):
                continue
        return result

    def adopt_legacy_artwork(self, task_ids):
        """Register only artwork with the exact filename format generated by us."""
        if not self.root.is_dir():
            return
        for task_id in task_ids:
            safe = re.sub(r"[^A-Za-z0-9_.-]", "_", task_id)
            pattern = re.compile(r"(?:thumb|cover)_" + re.escape(safe) + r"_(\d+)_[0-9a-f]{32}\.jpg")
            for file in self.root.iterdir():
                match = pattern.fullmatch(file.name)
                if match and file.is_file() and not file.is_symlink():
                    modified = file.stat().st_mtime
                    path = self.open(task_id, "legacy-artwork", [int(match[1])])
                    os.replace(file, path / file.name)
                    self.release(path)
                    atomic_json(path / OWNER_FILE, {"task_id": task_id, "updated_at": modified})

    def stats(self):
        result = {"files": 0, "bytes": 0, "workspaces": 0, "active": 0}
        for path, _ in self.directories():
            result["workspaces"] += 1
            result["active"] += int(path in ACTIVE_WORKSPACES)
            for file in path.iterdir():
                if file.is_file() and not file.is_symlink() and file.name != OWNER_FILE:
                    result["files"] += 1
                    result["bytes"] += file.stat().st_size
        return result

    def cleanup(self, task_id=None, max_age_hours=None, only_path=None):
        result = {"removed": 0, "freed_bytes": 0, "skipped_active": 0, "errors": []}
        for path, data in self.directories():
            if task_id is not None and data["task_id"] != task_id:
                continue
            if only_path is not None and path != Path(only_path).resolve():
                continue
            if path in ACTIVE_WORKSPACES:
                result["skipped_active"] += 1
                continue
            if max_age_hours is not None and (max_age_hours <= 0 or time.time() - data["updated_at"] < max_age_hours * 3600):
                continue
            try:
                files = [f for f in path.iterdir() if f.is_file() and not f.is_symlink() and f.name != OWNER_FILE]
                sizes = sum(f.stat().st_size for f in files)
                shutil.rmtree(path)
                result["removed"] += len(files)
                result["freed_bytes"] += sizes
                try:
                    path.parent.rmdir()
                except OSError:
                    pass
            except OSError as error:
                result["errors"].append({"path": str(path), "error": str(error)})
        return result
